# Generated by Django 4.2.7 on 2023-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_merge_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedboxorder',
            name='size_unit',
            field=models.CharField(max_length=10),
        ),
    ]
