# Generated by Django 4.2.7 on 2023-12-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_customizedboxorder_size_unit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customizedboxorder',
            name='size_unit',
            field=models.CharField(choices=[('inches', 'Inches'), ('cm', 'Centimeters')], max_length=10),
        ),
    ]
