# Generated by Django 4.2.7 on 2023-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consent_to_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='consent_to_save',
            field=models.BooleanField(default=False),
        ),
    ]
